# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'giris_kayit.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
#
#
# class Ui_Form(object):
#     def setupUi(self, Form):
#         Form.setObjectName("Form")
#         Form.resize(589, 563)
#         Form.setStyleSheet("QWidget {\n"
# "    background-color: rgb(244, 249, 255)\n"
# "}\n"
# "")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.label_2 = QtWidgets.QLabel(Form)
#         font = QtGui.QFont()
#         font.setPointSize(13)
#         font.setItalic(True)
#         self.label_2.setFont(font)
#         self.label_2.setAutoFillBackground(False)
#         self.label_2.setStyleSheet("color:rgb(0, 61, 90);")
#         self.label_2.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_2.setObjectName("label_2")
#         self.verticalLayout.addWidget(self.label_2)
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.horizontalLayout.setContentsMargins(0, -1, -1, 100)
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.pushButton_giris = QtWidgets.QPushButton(Form)
#         self.pushButton_giris.setMaximumSize(QtCore.QSize(250, 70))
#         font = QtGui.QFont()
#         font.setFamily("Georgia Pro Cond")
#         font.setPointSize(9)
#         font.setBold(False)
#         font.setItalic(False)
#         font.setUnderline(False)
#         font.setWeight(50)
#         font.setStrikeOut(False)
#         self.pushButton_giris.setFont(font)
#         self.pushButton_giris.setStyleSheet("QPushButton {\n"
# "    background-color:rgb(0, 85, 127);\n"
# "    color: white;\n"
# "    border-radius: 5px;\n"
# "    border: 1px solid #388E3C; \n"
# "}\n"
# "\n"
# "QPushButton:hover {\n"
# "    background-color:rgb(0, 131, 191);\n"
# "}\n"
# "\n"
# "")
#         self.pushButton_giris.setObjectName("pushButton_giris")
#         self.horizontalLayout.addWidget(self.pushButton_giris)
#         self.label = QtWidgets.QLabel(Form)
#         self.label.setMaximumSize(QtCore.QSize(100, 16777215))
#         font = QtGui.QFont()
#         font.setPointSize(9)
#         font.setItalic(False)
#         self.label.setFont(font)
#         self.label.setAlignment(QtCore.Qt.AlignCenter)
#         self.label.setObjectName("label")
#         self.horizontalLayout.addWidget(self.label)
#         self.pushButton_kayit = QtWidgets.QPushButton(Form)
#         self.pushButton_kayit.setMaximumSize(QtCore.QSize(250, 70))
#         font = QtGui.QFont()
#         font.setFamily("Georgia Pro Cond")
#         font.setPointSize(9)
#         font.setBold(False)
#         font.setItalic(False)
#         font.setWeight(50)
#         self.pushButton_kayit.setFont(font)
#         self.pushButton_kayit.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.pushButton_kayit.setStyleSheet("QPushButton {\n"
# "    background-color:rgb(0, 85, 127);\n"
# "    color: white;\n"
# "    border-radius: 5px;\n"
# "    border: 1px solid #388E3C; \n"
# "}\n"
# "\n"
# "QPushButton:hover {\n"
# "    background-color:rgb(0, 131, 191);\n"
# "}")
#         self.pushButton_kayit.setObjectName("pushButton_kayit")
#         self.horizontalLayout.addWidget(self.pushButton_kayit)
#         self.verticalLayout.addLayout(self.horizontalLayout)
#         self.verticalLayout_2.addLayout(self.verticalLayout)
#
#         self.retranslateUi(Form)
#         QtCore.QMetaObject.connectSlotsByName(Form)
#
#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Merhaba!"))
#         self.label_2.setText(_translate("Form", "Hava Durumu Uygulamasına Hoşgeldiniz !"))
#         self.pushButton_giris.setText(_translate("Form", "GİRİŞ YAP"))
#         self.label.setText(_translate("Form", "veya"))
#         self.pushButton_kayit.setText(_translate("Form", "KAYIT OL"))
#
#
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())

# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 563)
        Form.setStyleSheet("QWidget {\n"
                           "    background-color: rgb(244, 249, 255);\n"
                           "}")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # "Hava Durumu Uygulamasına Hoşgeldiniz!" Label
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(True)
        self.label_2.setFont(font)

        # Sadece bu label için arka plan resmi ayarlıyoruz
        self.label_2.setStyleSheet("""
            QLabel {
                color: #030032; /* Yazı rengini beyaz yapar */
                font-weight: bold;
                background-image: url("C:/Users/Feyza Nur/Desktop/görselprogramlama/projePyQt5/bulut.jpg");
                background-repeat: no-repeat;
                background-position: center;
                border-radius: 10px; /* Köşeleri yuvarlamak istersen */
            }
        """)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, 100)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Giriş Butonu
        self.pushButton_giris = QtWidgets.QPushButton(Form)
        self.pushButton_giris.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia Pro Cond")
        font.setPointSize(9)
        self.pushButton_giris.setFont(font)
        self.pushButton_giris.setStyleSheet("QPushButton {\n"
                                            "    background-color:rgb(0, 85, 127);\n"
                                            "    color: white;\n"
                                            "    border-radius: 5px;\n"
                                            "    border: 1px solid #388E3C; \n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color:rgb(0, 131, 191);\n"
                                            "}")
        self.pushButton_giris.setObjectName("pushButton_giris")
        self.horizontalLayout.addWidget(self.pushButton_giris)

        # "veya" yazısı
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        # Kayıt Ol Butonu
        self.pushButton_kayit = QtWidgets.QPushButton(Form)
        self.pushButton_kayit.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Georgia Pro Cond")
        font.setPointSize(9)
        self.pushButton_kayit.setFont(font)
        self.pushButton_kayit.setStyleSheet("QPushButton {\n"
                                            "    background-color:rgb(0, 85, 127);\n"
                                            "    color: white;\n"
                                            "    border-radius: 5px;\n"
                                            "    border: 1px solid #388E3C; \n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover {\n"
                                            "    background-color:rgb(0, 131, 191);\n"
                                            "}")
        self.pushButton_kayit.setObjectName("pushButton_kayit")
        self.horizontalLayout.addWidget(self.pushButton_kayit)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Merhaba!"))
        self.label_2.setText(_translate("Form", "Hava Durumu Uygulamasına Hoşgeldiniz !"))
        self.pushButton_giris.setText(_translate("Form", "GİRİŞ YAP"))
        self.label.setText(_translate("Form", "veya"))
        self.pushButton_kayit.setText(_translate("Form", "KAYIT OL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
