# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 350)
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(236, 236, 236)\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_kullanici_adi = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_kullanici_adi.sizePolicy().hasHeightForWidth())
        self.lineEdit_kullanici_adi.setSizePolicy(sizePolicy)
        self.lineEdit_kullanici_adi.setMaximumSize(QtCore.QSize(300, 30))
        self.lineEdit_kullanici_adi.setFrame(True)
        self.lineEdit_kullanici_adi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_kullanici_adi.setDragEnabled(False)
        self.lineEdit_kullanici_adi.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_kullanici_adi.setObjectName("lineEdit_kullanici_adi")
        self.verticalLayout.addWidget(self.lineEdit_kullanici_adi)
        self.lineEdit_sifre = QtWidgets.QLineEdit(Form)
        self.lineEdit_sifre.setMaximumSize(QtCore.QSize(300, 30))
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")
        self.verticalLayout.addWidget(self.lineEdit_sifre)
        self.pushButton_icgiris = QtWidgets.QPushButton(Form)
        self.pushButton_icgiris.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(False)
        font.setUnderline(True)
        self.pushButton_icgiris.setFont(font)
        self.pushButton_icgiris.setStyleSheet("QPushButton {\n"
"    background-color: rgb(194, 64, 82); /* Butonun arkaplan rengini yeşil yapar */\n"
"    color: white; /* Yazı rengini beyaz yapar */\n"
"    border-radius: 5px; /* Kenarları yuvarlar */\n"
"    border: 1px solid #388E3C; /* Kenarlık ekler */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 0, 0); /* Butonun üzerine gelindiğinde rengi değiştirir */\n"
"}\n"
"")
        self.pushButton_icgiris.setObjectName("pushButton_icgiris")
        self.verticalLayout.addWidget(self.pushButton_icgiris)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Giriş Yap"))
        self.lineEdit_kullanici_adi.setPlaceholderText(_translate("Form", "Kullanıcı Adınızı Girin"))
        self.lineEdit_sifre.setPlaceholderText(_translate("Form", "Şifrenizi Girin"))
        self.pushButton_icgiris.setText(_translate("Form", "GİRİŞ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
